version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Akash@123
      MYSQL_DATABASE: quantitymeasurementapp
    ports:
      - "3307:3306"
    networks:
      - microservices-net

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - microservices-net

  measurement-service:
    build: ./measurement-service
    container_name: measurement-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge